query GetLeadsGroupedByField($input: GroupLeadsInput!) {
  getLeadsGroupedByField(input: $input) {
       field
        groups {
            avgPrice
            count
            group
            totalPrice
            leads {
                awardCategory
                companyName
                country
                createdAt
                email
                id
                industry
                jobTitle
                leadType
                message
                name
                phone
                price
                projectId
                quantity
                status
                updatedAt
                utmId
            }
        }
    }
}