query GetLeadById($id: String!) {
  getLeadById(id: $id) {
    id
    projectId
    assignedToId
    name
    email
    additionalEmails
    phone
    additionalPhones
    companyName
    jobTitle
    contactPersonName
    contactPersonPhone
    contactPersonDesignation
    contactPersonEmail
    city
    state
    country
    industry
    status
    source
    leadType
    message
    notes
    quantity
    price
    assignedToId
    callbackDate
    followUpDate
    createdAt
    updatedAt
    assignedTo {
      id
      name
      email
      phone
      cities {
        city
        state
      }
    }
    utm {
      id
      source
      medium
      campaign
      term
      content
      url
    }
  }
}
